Update devsecops-pipeline.yml

diff --git a/.github/workflows/devsecops-pipeline.yml b/.github/workflows/devsecops-pipeline.yml
--- a/.github/workflows/devsecops-pipeline.yml
+++ b/.github/workflows/devsecops-pipeline.yml
@@ -1121,7 +1121,7 @@ jobs:
           railway up \
             --service shopvuln \
             --detach
-          echo "url=https://shopvuln.up.railway.app" >> $GITHUB_OUTPUT
+          echo "url=https://devsecops-pfe-production.up.railway.app" >> $GITHUB_OUTPUT
 
       - name: Smoke test
         run: |
@@ -1129,7 +1129,7 @@ jobs:
           sleep 20
           curl -f ${{ steps.deploy.outputs.url }} \
             && echo "SMOKE TEST PASSED — app is UP" \
-            || (echo "SMOKE TEST FAIILED — app did not respond" && exit 1)
+            || (echo "SMOKE TEST FAILED — app did not respond" && exit 1)
 
       - name: Upload deploy summary
         if: always()
